analyticsID: "G-VSFSCDCWCB"
year: "2022"
name: "Angeldust Duke"

owner: "Alexander Abraham"
menuText: "Menu"
url: "https://angeldustduke.art"
baseurl: ""
future: true

bg_image: "/assets/images/background/bg.svg"
uses_bg_image: true
uses_animation: false
mainColor: "#FFFFFF"
accentColor: "#000000"
hoverColor: "#808080"
headingFont: "Triest"
headingFontUrl: "https://blckunicorn.art/assets/fonts/Triest.ttf"
contentFont: "Schnyder"
contentFontUrl: "https://blckunicorn.art/assets/fonts/Schnyder.ttf"
bgColor: "#FFF"
waveColorOne: "7C40FF"
waveColorTwo: "#FF7BAC"
tertiaryFont: "Mono"
tertiaryFontUrl: "https://blckunicorn.art/assets/fonts/Mono.ttf"
codeColor: "#2B1F33"
copyFieldColor: "#282C33"

mainHeadingFont: "Hellraiser"
mainHeadingFontUrl: "https://blckunicorn.art/assets/fonts/Hellraiser.ttf"

# was -> {mainHeadingFont: "MC"}
# was -> {mainHeadingFontUrl: "https://blckunicorn.art/assets/fonts/MC.ttf"}
# was -> {name: "Angeldust Duke"}

logoDescription: "Diavorella"
footerText: "(C) 2021 ANGELDUST DUKE"
copiedText: "Link copied!"
specialEditonString: "SPECIAL EDITION"
avatar: "/assets/images/logo/logo.png"
bannerDescription: "Diavorella, the Angeldust Duke's muse."
banner: "https://angeldustduke.art/assets/images/banner/banner.png"
postsExist: true
closeText: "CLÖSË"
readPostText: "Read"
noPostText: "Regrettably, there are no posts yet! Check back regularly and visit the link below to stay tuned!"
noPostTitle: "No posts yet!"
noPostUrl: "https://twitter.com/angeldustduke"
viewNoPostUrl: "Visit"
keywords: "developer, code, flutter, dart, rust lang, blogging, art, python, compiler"
iconsPresent: true
iconUrlIsAbsolute: false
57x57: "/assets/images/favicons/apple-icon-57x57.png"
60x60: "/assets/images/favicons/apple-icon-60x60.png"
72x72: "/assets/images/favicons/apple-icon-72x72.png"
76x76: "/assets/images/favicons/apple-icon-76x76.png"
114x114: "/assets/images/favicons/apple-icon-114x114.png"
120x120: "/assets/images/favicons/apple-icon-120x120.png"
144x144: "/assets/images/favicons/apple-icon-144x144.png"
152x152: "/assets/images/favicons/apple-icon-152x152.png"
180x180: "/assets/images/favicons/apple-icon-180x180.png"
192x192: "/assets/images/favicons/android-icon-192x192.png"
32x32: "/assets/images/favicons/favicon-32x32.png"
96x96: "/assets/images/favicons/favicon-96x96.png"
16x16: "/assets/images/favicons/favicon-16x16.png"
siteManifest: "/assets/images/favicons/manifest.json"
144x144: "/assets/images/favicons/ms-icon-144x144.png"
description: "Angeldust Duke: a bad b*tch, a creative soul, and eccentric as f*ck."
feed:
  path: "rss.xml"
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - sassc
